/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountSettingsRouteImport } from './routes/account-settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScanCreateItemRouteImport } from './routes/scan.create-item'
import { Route as CatalogLineIdRouteImport } from './routes/catalog.$lineId'
import { Route as ApiPostsRouteImport } from './routes/api/posts'
import { Route as ApiCommentsRouteImport } from './routes/api/comments'
import { Route as ApiAccountSettingsRouteImport } from './routes/api/account-settings'
import { Route as ApiCatalogIndexRouteImport } from './routes/api/catalog/index'
import { Route as ApiScanSearchRouteImport } from './routes/api/scan/search'
import { Route as ApiScanResolveRouteImport } from './routes/api/scan/resolve'
import { Route as ApiScanInventoryRouteImport } from './routes/api/scan/inventory'
import { Route as ApiScanCreateItemRouteImport } from './routes/api/scan/create-item'
import { Route as ApiScanAssociateRouteImport } from './routes/api/scan/associate'
import { Route as ApiPatternsPublicRouteImport } from './routes/api/patterns/public'
import { Route as ApiDiscoverFeedRouteImport } from './routes/api/discover/feed'
import { Route as ApiCommunityFlagsRouteImport } from './routes/api/community/flags'
import { Route as ApiCommunityClaimsRouteImport } from './routes/api/community/claims'
import { Route as ApiCatalogLineIdRouteImport } from './routes/api/catalog/$lineId'
import { Route as ApiAuthSignUpRouteImport } from './routes/api/auth/sign-up'
import { Route as ApiAuthSignOutRouteImport } from './routes/api/auth/sign-out'
import { Route as ApiAuthSignInRouteImport } from './routes/api/auth/sign-in'
import { Route as ApiAuthResetPasswordRouteImport } from './routes/api/auth/reset-password'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthForgotPasswordRouteImport } from './routes/api/auth/forgot-password'
import { Route as ApiAdminOverviewRouteImport } from './routes/api/admin/overview'
import { Route as ApiAccountSettingsPasswordRouteImport } from './routes/api/account-settings/password'
import { Route as ApiAccountSettingsAvatarRouteImport } from './routes/api/account-settings/avatar'
import { Route as ApiPostsPostIdImagesRouteImport } from './routes/api/posts/$postId/images'
import { Route as ApiPatternsPatternIdUploadRouteImport } from './routes/api/patterns/$patternId/upload'
import { Route as ApiPatternsPatternIdFileRouteImport } from './routes/api/patterns/$patternId/file'
import { Route as ApiPatternsPatternIdCoverRouteImport } from './routes/api/patterns/$patternId/cover'
import { Route as ApiPatternsPatternIdClaimRouteImport } from './routes/api/patterns/$patternId/claim'
import { Route as ApiCreationsCreationIdImagesRouteImport } from './routes/api/creations/$creationId/images'
import { Route as ApiCatalogLineIdBarcodesRouteImport } from './routes/api/catalog/$lineId/barcodes'
import { Route as ApiCommunityClaimsClaimIdVoteRouteImport } from './routes/api/community/claims/$claimId/vote'
import { Route as ApiAdminUsersUserIdRoleRouteImport } from './routes/api/admin/users/$userId/role'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/account-settings',
  path: '/account-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanCreateItemRoute = ScanCreateItemRouteImport.update({
  id: '/create-item',
  path: '/create-item',
  getParentRoute: () => ScanRoute,
} as any)
const CatalogLineIdRoute = CatalogLineIdRouteImport.update({
  id: '/$lineId',
  path: '/$lineId',
  getParentRoute: () => CatalogRoute,
} as any)
const ApiPostsRoute = ApiPostsRouteImport.update({
  id: '/api/posts',
  path: '/api/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommentsRoute = ApiCommentsRouteImport.update({
  id: '/api/comments',
  path: '/api/comments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountSettingsRoute = ApiAccountSettingsRouteImport.update({
  id: '/api/account-settings',
  path: '/api/account-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalogIndexRoute = ApiCatalogIndexRouteImport.update({
  id: '/api/catalog/',
  path: '/api/catalog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScanSearchRoute = ApiScanSearchRouteImport.update({
  id: '/api/scan/search',
  path: '/api/scan/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScanResolveRoute = ApiScanResolveRouteImport.update({
  id: '/api/scan/resolve',
  path: '/api/scan/resolve',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScanInventoryRoute = ApiScanInventoryRouteImport.update({
  id: '/api/scan/inventory',
  path: '/api/scan/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScanCreateItemRoute = ApiScanCreateItemRouteImport.update({
  id: '/api/scan/create-item',
  path: '/api/scan/create-item',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScanAssociateRoute = ApiScanAssociateRouteImport.update({
  id: '/api/scan/associate',
  path: '/api/scan/associate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPatternsPublicRoute = ApiPatternsPublicRouteImport.update({
  id: '/api/patterns/public',
  path: '/api/patterns/public',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiscoverFeedRoute = ApiDiscoverFeedRouteImport.update({
  id: '/api/discover/feed',
  path: '/api/discover/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommunityFlagsRoute = ApiCommunityFlagsRouteImport.update({
  id: '/api/community/flags',
  path: '/api/community/flags',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommunityClaimsRoute = ApiCommunityClaimsRouteImport.update({
  id: '/api/community/claims',
  path: '/api/community/claims',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalogLineIdRoute = ApiCatalogLineIdRouteImport.update({
  id: '/api/catalog/$lineId',
  path: '/api/catalog/$lineId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignUpRoute = ApiAuthSignUpRouteImport.update({
  id: '/api/auth/sign-up',
  path: '/api/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignOutRoute = ApiAuthSignOutRouteImport.update({
  id: '/api/auth/sign-out',
  path: '/api/auth/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignInRoute = ApiAuthSignInRouteImport.update({
  id: '/api/auth/sign-in',
  path: '/api/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthResetPasswordRoute = ApiAuthResetPasswordRouteImport.update({
  id: '/api/auth/reset-password',
  path: '/api/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthForgotPasswordRoute = ApiAuthForgotPasswordRouteImport.update({
  id: '/api/auth/forgot-password',
  path: '/api/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminOverviewRoute = ApiAdminOverviewRouteImport.update({
  id: '/api/admin/overview',
  path: '/api/admin/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountSettingsPasswordRoute =
  ApiAccountSettingsPasswordRouteImport.update({
    id: '/password',
    path: '/password',
    getParentRoute: () => ApiAccountSettingsRoute,
  } as any)
const ApiAccountSettingsAvatarRoute =
  ApiAccountSettingsAvatarRouteImport.update({
    id: '/avatar',
    path: '/avatar',
    getParentRoute: () => ApiAccountSettingsRoute,
  } as any)
const ApiPostsPostIdImagesRoute = ApiPostsPostIdImagesRouteImport.update({
  id: '/$postId/images',
  path: '/$postId/images',
  getParentRoute: () => ApiPostsRoute,
} as any)
const ApiPatternsPatternIdUploadRoute =
  ApiPatternsPatternIdUploadRouteImport.update({
    id: '/api/patterns/$patternId/upload',
    path: '/api/patterns/$patternId/upload',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPatternsPatternIdFileRoute =
  ApiPatternsPatternIdFileRouteImport.update({
    id: '/api/patterns/$patternId/file',
    path: '/api/patterns/$patternId/file',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPatternsPatternIdCoverRoute =
  ApiPatternsPatternIdCoverRouteImport.update({
    id: '/api/patterns/$patternId/cover',
    path: '/api/patterns/$patternId/cover',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPatternsPatternIdClaimRoute =
  ApiPatternsPatternIdClaimRouteImport.update({
    id: '/api/patterns/$patternId/claim',
    path: '/api/patterns/$patternId/claim',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCreationsCreationIdImagesRoute =
  ApiCreationsCreationIdImagesRouteImport.update({
    id: '/api/creations/$creationId/images',
    path: '/api/creations/$creationId/images',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCatalogLineIdBarcodesRoute =
  ApiCatalogLineIdBarcodesRouteImport.update({
    id: '/barcodes',
    path: '/barcodes',
    getParentRoute: () => ApiCatalogLineIdRoute,
  } as any)
const ApiCommunityClaimsClaimIdVoteRoute =
  ApiCommunityClaimsClaimIdVoteRouteImport.update({
    id: '/$claimId/vote',
    path: '/$claimId/vote',
    getParentRoute: () => ApiCommunityClaimsRoute,
  } as any)
const ApiAdminUsersUserIdRoleRoute = ApiAdminUsersUserIdRoleRouteImport.update({
  id: '/api/admin/users/$userId/role',
  path: '/api/admin/users/$userId/role',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account-settings': typeof AccountSettingsRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/catalog': typeof CatalogRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inventory': typeof InventoryRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scan': typeof ScanRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/api/account-settings': typeof ApiAccountSettingsRouteWithChildren
  '/api/comments': typeof ApiCommentsRoute
  '/api/posts': typeof ApiPostsRouteWithChildren
  '/catalog/$lineId': typeof CatalogLineIdRoute
  '/scan/create-item': typeof ScanCreateItemRoute
  '/api/account-settings/avatar': typeof ApiAccountSettingsAvatarRoute
  '/api/account-settings/password': typeof ApiAccountSettingsPasswordRoute
  '/api/admin/overview': typeof ApiAdminOverviewRoute
  '/api/auth/forgot-password': typeof ApiAuthForgotPasswordRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/reset-password': typeof ApiAuthResetPasswordRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute
  '/api/auth/sign-up': typeof ApiAuthSignUpRoute
  '/api/catalog/$lineId': typeof ApiCatalogLineIdRouteWithChildren
  '/api/community/claims': typeof ApiCommunityClaimsRouteWithChildren
  '/api/community/flags': typeof ApiCommunityFlagsRoute
  '/api/discover/feed': typeof ApiDiscoverFeedRoute
  '/api/patterns/public': typeof ApiPatternsPublicRoute
  '/api/scan/associate': typeof ApiScanAssociateRoute
  '/api/scan/create-item': typeof ApiScanCreateItemRoute
  '/api/scan/inventory': typeof ApiScanInventoryRoute
  '/api/scan/resolve': typeof ApiScanResolveRoute
  '/api/scan/search': typeof ApiScanSearchRoute
  '/api/catalog/': typeof ApiCatalogIndexRoute
  '/api/catalog/$lineId/barcodes': typeof ApiCatalogLineIdBarcodesRoute
  '/api/creations/$creationId/images': typeof ApiCreationsCreationIdImagesRoute
  '/api/patterns/$patternId/claim': typeof ApiPatternsPatternIdClaimRoute
  '/api/patterns/$patternId/cover': typeof ApiPatternsPatternIdCoverRoute
  '/api/patterns/$patternId/file': typeof ApiPatternsPatternIdFileRoute
  '/api/patterns/$patternId/upload': typeof ApiPatternsPatternIdUploadRoute
  '/api/posts/$postId/images': typeof ApiPostsPostIdImagesRoute
  '/api/admin/users/$userId/role': typeof ApiAdminUsersUserIdRoleRoute
  '/api/community/claims/$claimId/vote': typeof ApiCommunityClaimsClaimIdVoteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account-settings': typeof AccountSettingsRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/catalog': typeof CatalogRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inventory': typeof InventoryRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scan': typeof ScanRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/api/account-settings': typeof ApiAccountSettingsRouteWithChildren
  '/api/comments': typeof ApiCommentsRoute
  '/api/posts': typeof ApiPostsRouteWithChildren
  '/catalog/$lineId': typeof CatalogLineIdRoute
  '/scan/create-item': typeof ScanCreateItemRoute
  '/api/account-settings/avatar': typeof ApiAccountSettingsAvatarRoute
  '/api/account-settings/password': typeof ApiAccountSettingsPasswordRoute
  '/api/admin/overview': typeof ApiAdminOverviewRoute
  '/api/auth/forgot-password': typeof ApiAuthForgotPasswordRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/reset-password': typeof ApiAuthResetPasswordRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute
  '/api/auth/sign-up': typeof ApiAuthSignUpRoute
  '/api/catalog/$lineId': typeof ApiCatalogLineIdRouteWithChildren
  '/api/community/claims': typeof ApiCommunityClaimsRouteWithChildren
  '/api/community/flags': typeof ApiCommunityFlagsRoute
  '/api/discover/feed': typeof ApiDiscoverFeedRoute
  '/api/patterns/public': typeof ApiPatternsPublicRoute
  '/api/scan/associate': typeof ApiScanAssociateRoute
  '/api/scan/create-item': typeof ApiScanCreateItemRoute
  '/api/scan/inventory': typeof ApiScanInventoryRoute
  '/api/scan/resolve': typeof ApiScanResolveRoute
  '/api/scan/search': typeof ApiScanSearchRoute
  '/api/catalog': typeof ApiCatalogIndexRoute
  '/api/catalog/$lineId/barcodes': typeof ApiCatalogLineIdBarcodesRoute
  '/api/creations/$creationId/images': typeof ApiCreationsCreationIdImagesRoute
  '/api/patterns/$patternId/claim': typeof ApiPatternsPatternIdClaimRoute
  '/api/patterns/$patternId/cover': typeof ApiPatternsPatternIdCoverRoute
  '/api/patterns/$patternId/file': typeof ApiPatternsPatternIdFileRoute
  '/api/patterns/$patternId/upload': typeof ApiPatternsPatternIdUploadRoute
  '/api/posts/$postId/images': typeof ApiPostsPostIdImagesRoute
  '/api/admin/users/$userId/role': typeof ApiAdminUsersUserIdRoleRoute
  '/api/community/claims/$claimId/vote': typeof ApiCommunityClaimsClaimIdVoteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account-settings': typeof AccountSettingsRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/catalog': typeof CatalogRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inventory': typeof InventoryRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scan': typeof ScanRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/api/account-settings': typeof ApiAccountSettingsRouteWithChildren
  '/api/comments': typeof ApiCommentsRoute
  '/api/posts': typeof ApiPostsRouteWithChildren
  '/catalog/$lineId': typeof CatalogLineIdRoute
  '/scan/create-item': typeof ScanCreateItemRoute
  '/api/account-settings/avatar': typeof ApiAccountSettingsAvatarRoute
  '/api/account-settings/password': typeof ApiAccountSettingsPasswordRoute
  '/api/admin/overview': typeof ApiAdminOverviewRoute
  '/api/auth/forgot-password': typeof ApiAuthForgotPasswordRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/reset-password': typeof ApiAuthResetPasswordRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute
  '/api/auth/sign-up': typeof ApiAuthSignUpRoute
  '/api/catalog/$lineId': typeof ApiCatalogLineIdRouteWithChildren
  '/api/community/claims': typeof ApiCommunityClaimsRouteWithChildren
  '/api/community/flags': typeof ApiCommunityFlagsRoute
  '/api/discover/feed': typeof ApiDiscoverFeedRoute
  '/api/patterns/public': typeof ApiPatternsPublicRoute
  '/api/scan/associate': typeof ApiScanAssociateRoute
  '/api/scan/create-item': typeof ApiScanCreateItemRoute
  '/api/scan/inventory': typeof ApiScanInventoryRoute
  '/api/scan/resolve': typeof ApiScanResolveRoute
  '/api/scan/search': typeof ApiScanSearchRoute
  '/api/catalog/': typeof ApiCatalogIndexRoute
  '/api/catalog/$lineId/barcodes': typeof ApiCatalogLineIdBarcodesRoute
  '/api/creations/$creationId/images': typeof ApiCreationsCreationIdImagesRoute
  '/api/patterns/$patternId/claim': typeof ApiPatternsPatternIdClaimRoute
  '/api/patterns/$patternId/cover': typeof ApiPatternsPatternIdCoverRoute
  '/api/patterns/$patternId/file': typeof ApiPatternsPatternIdFileRoute
  '/api/patterns/$patternId/upload': typeof ApiPatternsPatternIdUploadRoute
  '/api/posts/$postId/images': typeof ApiPostsPostIdImagesRoute
  '/api/admin/users/$userId/role': typeof ApiAdminUsersUserIdRoleRoute
  '/api/community/claims/$claimId/vote': typeof ApiCommunityClaimsClaimIdVoteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-settings'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/catalog'
    | '/dashboard'
    | '/forgot-password'
    | '/inventory'
    | '/register'
    | '/reset-password'
    | '/scan'
    | '/sign-in'
    | '/api/account-settings'
    | '/api/comments'
    | '/api/posts'
    | '/catalog/$lineId'
    | '/scan/create-item'
    | '/api/account-settings/avatar'
    | '/api/account-settings/password'
    | '/api/admin/overview'
    | '/api/auth/forgot-password'
    | '/api/auth/me'
    | '/api/auth/reset-password'
    | '/api/auth/sign-in'
    | '/api/auth/sign-out'
    | '/api/auth/sign-up'
    | '/api/catalog/$lineId'
    | '/api/community/claims'
    | '/api/community/flags'
    | '/api/discover/feed'
    | '/api/patterns/public'
    | '/api/scan/associate'
    | '/api/scan/create-item'
    | '/api/scan/inventory'
    | '/api/scan/resolve'
    | '/api/scan/search'
    | '/api/catalog/'
    | '/api/catalog/$lineId/barcodes'
    | '/api/creations/$creationId/images'
    | '/api/patterns/$patternId/claim'
    | '/api/patterns/$patternId/cover'
    | '/api/patterns/$patternId/file'
    | '/api/patterns/$patternId/upload'
    | '/api/posts/$postId/images'
    | '/api/admin/users/$userId/role'
    | '/api/community/claims/$claimId/vote'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-settings'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/catalog'
    | '/dashboard'
    | '/forgot-password'
    | '/inventory'
    | '/register'
    | '/reset-password'
    | '/scan'
    | '/sign-in'
    | '/api/account-settings'
    | '/api/comments'
    | '/api/posts'
    | '/catalog/$lineId'
    | '/scan/create-item'
    | '/api/account-settings/avatar'
    | '/api/account-settings/password'
    | '/api/admin/overview'
    | '/api/auth/forgot-password'
    | '/api/auth/me'
    | '/api/auth/reset-password'
    | '/api/auth/sign-in'
    | '/api/auth/sign-out'
    | '/api/auth/sign-up'
    | '/api/catalog/$lineId'
    | '/api/community/claims'
    | '/api/community/flags'
    | '/api/discover/feed'
    | '/api/patterns/public'
    | '/api/scan/associate'
    | '/api/scan/create-item'
    | '/api/scan/inventory'
    | '/api/scan/resolve'
    | '/api/scan/search'
    | '/api/catalog'
    | '/api/catalog/$lineId/barcodes'
    | '/api/creations/$creationId/images'
    | '/api/patterns/$patternId/claim'
    | '/api/patterns/$patternId/cover'
    | '/api/patterns/$patternId/file'
    | '/api/patterns/$patternId/upload'
    | '/api/posts/$postId/images'
    | '/api/admin/users/$userId/role'
    | '/api/community/claims/$claimId/vote'
  id:
    | '__root__'
    | '/'
    | '/account-settings'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/catalog'
    | '/dashboard'
    | '/forgot-password'
    | '/inventory'
    | '/register'
    | '/reset-password'
    | '/scan'
    | '/sign-in'
    | '/api/account-settings'
    | '/api/comments'
    | '/api/posts'
    | '/catalog/$lineId'
    | '/scan/create-item'
    | '/api/account-settings/avatar'
    | '/api/account-settings/password'
    | '/api/admin/overview'
    | '/api/auth/forgot-password'
    | '/api/auth/me'
    | '/api/auth/reset-password'
    | '/api/auth/sign-in'
    | '/api/auth/sign-out'
    | '/api/auth/sign-up'
    | '/api/catalog/$lineId'
    | '/api/community/claims'
    | '/api/community/flags'
    | '/api/discover/feed'
    | '/api/patterns/public'
    | '/api/scan/associate'
    | '/api/scan/create-item'
    | '/api/scan/inventory'
    | '/api/scan/resolve'
    | '/api/scan/search'
    | '/api/catalog/'
    | '/api/catalog/$lineId/barcodes'
    | '/api/creations/$creationId/images'
    | '/api/patterns/$patternId/claim'
    | '/api/patterns/$patternId/cover'
    | '/api/patterns/$patternId/file'
    | '/api/patterns/$patternId/upload'
    | '/api/posts/$postId/images'
    | '/api/admin/users/$userId/role'
    | '/api/community/claims/$claimId/vote'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountSettingsRoute: typeof AccountSettingsRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRoute
  CatalogRoute: typeof CatalogRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InventoryRoute: typeof InventoryRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ScanRoute: typeof ScanRouteWithChildren
  SignInRoute: typeof SignInRoute
  ApiAccountSettingsRoute: typeof ApiAccountSettingsRouteWithChildren
  ApiCommentsRoute: typeof ApiCommentsRoute
  ApiPostsRoute: typeof ApiPostsRouteWithChildren
  ApiAdminOverviewRoute: typeof ApiAdminOverviewRoute
  ApiAuthForgotPasswordRoute: typeof ApiAuthForgotPasswordRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthResetPasswordRoute: typeof ApiAuthResetPasswordRoute
  ApiAuthSignInRoute: typeof ApiAuthSignInRoute
  ApiAuthSignOutRoute: typeof ApiAuthSignOutRoute
  ApiAuthSignUpRoute: typeof ApiAuthSignUpRoute
  ApiCatalogLineIdRoute: typeof ApiCatalogLineIdRouteWithChildren
  ApiCommunityClaimsRoute: typeof ApiCommunityClaimsRouteWithChildren
  ApiCommunityFlagsRoute: typeof ApiCommunityFlagsRoute
  ApiDiscoverFeedRoute: typeof ApiDiscoverFeedRoute
  ApiPatternsPublicRoute: typeof ApiPatternsPublicRoute
  ApiScanAssociateRoute: typeof ApiScanAssociateRoute
  ApiScanCreateItemRoute: typeof ApiScanCreateItemRoute
  ApiScanInventoryRoute: typeof ApiScanInventoryRoute
  ApiScanResolveRoute: typeof ApiScanResolveRoute
  ApiScanSearchRoute: typeof ApiScanSearchRoute
  ApiCatalogIndexRoute: typeof ApiCatalogIndexRoute
  ApiCreationsCreationIdImagesRoute: typeof ApiCreationsCreationIdImagesRoute
  ApiPatternsPatternIdClaimRoute: typeof ApiPatternsPatternIdClaimRoute
  ApiPatternsPatternIdCoverRoute: typeof ApiPatternsPatternIdCoverRoute
  ApiPatternsPatternIdFileRoute: typeof ApiPatternsPatternIdFileRoute
  ApiPatternsPatternIdUploadRoute: typeof ApiPatternsPatternIdUploadRoute
  ApiAdminUsersUserIdRoleRoute: typeof ApiAdminUsersUserIdRoleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-settings': {
      id: '/account-settings'
      path: '/account-settings'
      fullPath: '/account-settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/create-item': {
      id: '/scan/create-item'
      path: '/create-item'
      fullPath: '/scan/create-item'
      preLoaderRoute: typeof ScanCreateItemRouteImport
      parentRoute: typeof ScanRoute
    }
    '/catalog/$lineId': {
      id: '/catalog/$lineId'
      path: '/$lineId'
      fullPath: '/catalog/$lineId'
      preLoaderRoute: typeof CatalogLineIdRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/api/posts': {
      id: '/api/posts'
      path: '/api/posts'
      fullPath: '/api/posts'
      preLoaderRoute: typeof ApiPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/comments': {
      id: '/api/comments'
      path: '/api/comments'
      fullPath: '/api/comments'
      preLoaderRoute: typeof ApiCommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account-settings': {
      id: '/api/account-settings'
      path: '/api/account-settings'
      fullPath: '/api/account-settings'
      preLoaderRoute: typeof ApiAccountSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalog/': {
      id: '/api/catalog/'
      path: '/api/catalog'
      fullPath: '/api/catalog/'
      preLoaderRoute: typeof ApiCatalogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scan/search': {
      id: '/api/scan/search'
      path: '/api/scan/search'
      fullPath: '/api/scan/search'
      preLoaderRoute: typeof ApiScanSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scan/resolve': {
      id: '/api/scan/resolve'
      path: '/api/scan/resolve'
      fullPath: '/api/scan/resolve'
      preLoaderRoute: typeof ApiScanResolveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scan/inventory': {
      id: '/api/scan/inventory'
      path: '/api/scan/inventory'
      fullPath: '/api/scan/inventory'
      preLoaderRoute: typeof ApiScanInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scan/create-item': {
      id: '/api/scan/create-item'
      path: '/api/scan/create-item'
      fullPath: '/api/scan/create-item'
      preLoaderRoute: typeof ApiScanCreateItemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scan/associate': {
      id: '/api/scan/associate'
      path: '/api/scan/associate'
      fullPath: '/api/scan/associate'
      preLoaderRoute: typeof ApiScanAssociateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/patterns/public': {
      id: '/api/patterns/public'
      path: '/api/patterns/public'
      fullPath: '/api/patterns/public'
      preLoaderRoute: typeof ApiPatternsPublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/discover/feed': {
      id: '/api/discover/feed'
      path: '/api/discover/feed'
      fullPath: '/api/discover/feed'
      preLoaderRoute: typeof ApiDiscoverFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/community/flags': {
      id: '/api/community/flags'
      path: '/api/community/flags'
      fullPath: '/api/community/flags'
      preLoaderRoute: typeof ApiCommunityFlagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/community/claims': {
      id: '/api/community/claims'
      path: '/api/community/claims'
      fullPath: '/api/community/claims'
      preLoaderRoute: typeof ApiCommunityClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalog/$lineId': {
      id: '/api/catalog/$lineId'
      path: '/api/catalog/$lineId'
      fullPath: '/api/catalog/$lineId'
      preLoaderRoute: typeof ApiCatalogLineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-up': {
      id: '/api/auth/sign-up'
      path: '/api/auth/sign-up'
      fullPath: '/api/auth/sign-up'
      preLoaderRoute: typeof ApiAuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-out': {
      id: '/api/auth/sign-out'
      path: '/api/auth/sign-out'
      fullPath: '/api/auth/sign-out'
      preLoaderRoute: typeof ApiAuthSignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-in': {
      id: '/api/auth/sign-in'
      path: '/api/auth/sign-in'
      fullPath: '/api/auth/sign-in'
      preLoaderRoute: typeof ApiAuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/reset-password': {
      id: '/api/auth/reset-password'
      path: '/api/auth/reset-password'
      fullPath: '/api/auth/reset-password'
      preLoaderRoute: typeof ApiAuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/forgot-password': {
      id: '/api/auth/forgot-password'
      path: '/api/auth/forgot-password'
      fullPath: '/api/auth/forgot-password'
      preLoaderRoute: typeof ApiAuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/overview': {
      id: '/api/admin/overview'
      path: '/api/admin/overview'
      fullPath: '/api/admin/overview'
      preLoaderRoute: typeof ApiAdminOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account-settings/password': {
      id: '/api/account-settings/password'
      path: '/password'
      fullPath: '/api/account-settings/password'
      preLoaderRoute: typeof ApiAccountSettingsPasswordRouteImport
      parentRoute: typeof ApiAccountSettingsRoute
    }
    '/api/account-settings/avatar': {
      id: '/api/account-settings/avatar'
      path: '/avatar'
      fullPath: '/api/account-settings/avatar'
      preLoaderRoute: typeof ApiAccountSettingsAvatarRouteImport
      parentRoute: typeof ApiAccountSettingsRoute
    }
    '/api/posts/$postId/images': {
      id: '/api/posts/$postId/images'
      path: '/$postId/images'
      fullPath: '/api/posts/$postId/images'
      preLoaderRoute: typeof ApiPostsPostIdImagesRouteImport
      parentRoute: typeof ApiPostsRoute
    }
    '/api/patterns/$patternId/upload': {
      id: '/api/patterns/$patternId/upload'
      path: '/api/patterns/$patternId/upload'
      fullPath: '/api/patterns/$patternId/upload'
      preLoaderRoute: typeof ApiPatternsPatternIdUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/patterns/$patternId/file': {
      id: '/api/patterns/$patternId/file'
      path: '/api/patterns/$patternId/file'
      fullPath: '/api/patterns/$patternId/file'
      preLoaderRoute: typeof ApiPatternsPatternIdFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/patterns/$patternId/cover': {
      id: '/api/patterns/$patternId/cover'
      path: '/api/patterns/$patternId/cover'
      fullPath: '/api/patterns/$patternId/cover'
      preLoaderRoute: typeof ApiPatternsPatternIdCoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/patterns/$patternId/claim': {
      id: '/api/patterns/$patternId/claim'
      path: '/api/patterns/$patternId/claim'
      fullPath: '/api/patterns/$patternId/claim'
      preLoaderRoute: typeof ApiPatternsPatternIdClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/creations/$creationId/images': {
      id: '/api/creations/$creationId/images'
      path: '/api/creations/$creationId/images'
      fullPath: '/api/creations/$creationId/images'
      preLoaderRoute: typeof ApiCreationsCreationIdImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalog/$lineId/barcodes': {
      id: '/api/catalog/$lineId/barcodes'
      path: '/barcodes'
      fullPath: '/api/catalog/$lineId/barcodes'
      preLoaderRoute: typeof ApiCatalogLineIdBarcodesRouteImport
      parentRoute: typeof ApiCatalogLineIdRoute
    }
    '/api/community/claims/$claimId/vote': {
      id: '/api/community/claims/$claimId/vote'
      path: '/$claimId/vote'
      fullPath: '/api/community/claims/$claimId/vote'
      preLoaderRoute: typeof ApiCommunityClaimsClaimIdVoteRouteImport
      parentRoute: typeof ApiCommunityClaimsRoute
    }
    '/api/admin/users/$userId/role': {
      id: '/api/admin/users/$userId/role'
      path: '/api/admin/users/$userId/role'
      fullPath: '/api/admin/users/$userId/role'
      preLoaderRoute: typeof ApiAdminUsersUserIdRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CatalogRouteChildren {
  CatalogLineIdRoute: typeof CatalogLineIdRoute
}

const CatalogRouteChildren: CatalogRouteChildren = {
  CatalogLineIdRoute: CatalogLineIdRoute,
}

const CatalogRouteWithChildren =
  CatalogRoute._addFileChildren(CatalogRouteChildren)

interface ScanRouteChildren {
  ScanCreateItemRoute: typeof ScanCreateItemRoute
}

const ScanRouteChildren: ScanRouteChildren = {
  ScanCreateItemRoute: ScanCreateItemRoute,
}

const ScanRouteWithChildren = ScanRoute._addFileChildren(ScanRouteChildren)

interface ApiAccountSettingsRouteChildren {
  ApiAccountSettingsAvatarRoute: typeof ApiAccountSettingsAvatarRoute
  ApiAccountSettingsPasswordRoute: typeof ApiAccountSettingsPasswordRoute
}

const ApiAccountSettingsRouteChildren: ApiAccountSettingsRouteChildren = {
  ApiAccountSettingsAvatarRoute: ApiAccountSettingsAvatarRoute,
  ApiAccountSettingsPasswordRoute: ApiAccountSettingsPasswordRoute,
}

const ApiAccountSettingsRouteWithChildren =
  ApiAccountSettingsRoute._addFileChildren(ApiAccountSettingsRouteChildren)

interface ApiPostsRouteChildren {
  ApiPostsPostIdImagesRoute: typeof ApiPostsPostIdImagesRoute
}

const ApiPostsRouteChildren: ApiPostsRouteChildren = {
  ApiPostsPostIdImagesRoute: ApiPostsPostIdImagesRoute,
}

const ApiPostsRouteWithChildren = ApiPostsRoute._addFileChildren(
  ApiPostsRouteChildren,
)

interface ApiCatalogLineIdRouteChildren {
  ApiCatalogLineIdBarcodesRoute: typeof ApiCatalogLineIdBarcodesRoute
}

const ApiCatalogLineIdRouteChildren: ApiCatalogLineIdRouteChildren = {
  ApiCatalogLineIdBarcodesRoute: ApiCatalogLineIdBarcodesRoute,
}

const ApiCatalogLineIdRouteWithChildren =
  ApiCatalogLineIdRoute._addFileChildren(ApiCatalogLineIdRouteChildren)

interface ApiCommunityClaimsRouteChildren {
  ApiCommunityClaimsClaimIdVoteRoute: typeof ApiCommunityClaimsClaimIdVoteRoute
}

const ApiCommunityClaimsRouteChildren: ApiCommunityClaimsRouteChildren = {
  ApiCommunityClaimsClaimIdVoteRoute: ApiCommunityClaimsClaimIdVoteRoute,
}

const ApiCommunityClaimsRouteWithChildren =
  ApiCommunityClaimsRoute._addFileChildren(ApiCommunityClaimsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountSettingsRoute: AccountSettingsRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRoute,
  CatalogRoute: CatalogRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InventoryRoute: InventoryRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ScanRoute: ScanRouteWithChildren,
  SignInRoute: SignInRoute,
  ApiAccountSettingsRoute: ApiAccountSettingsRouteWithChildren,
  ApiCommentsRoute: ApiCommentsRoute,
  ApiPostsRoute: ApiPostsRouteWithChildren,
  ApiAdminOverviewRoute: ApiAdminOverviewRoute,
  ApiAuthForgotPasswordRoute: ApiAuthForgotPasswordRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthResetPasswordRoute: ApiAuthResetPasswordRoute,
  ApiAuthSignInRoute: ApiAuthSignInRoute,
  ApiAuthSignOutRoute: ApiAuthSignOutRoute,
  ApiAuthSignUpRoute: ApiAuthSignUpRoute,
  ApiCatalogLineIdRoute: ApiCatalogLineIdRouteWithChildren,
  ApiCommunityClaimsRoute: ApiCommunityClaimsRouteWithChildren,
  ApiCommunityFlagsRoute: ApiCommunityFlagsRoute,
  ApiDiscoverFeedRoute: ApiDiscoverFeedRoute,
  ApiPatternsPublicRoute: ApiPatternsPublicRoute,
  ApiScanAssociateRoute: ApiScanAssociateRoute,
  ApiScanCreateItemRoute: ApiScanCreateItemRoute,
  ApiScanInventoryRoute: ApiScanInventoryRoute,
  ApiScanResolveRoute: ApiScanResolveRoute,
  ApiScanSearchRoute: ApiScanSearchRoute,
  ApiCatalogIndexRoute: ApiCatalogIndexRoute,
  ApiCreationsCreationIdImagesRoute: ApiCreationsCreationIdImagesRoute,
  ApiPatternsPatternIdClaimRoute: ApiPatternsPatternIdClaimRoute,
  ApiPatternsPatternIdCoverRoute: ApiPatternsPatternIdCoverRoute,
  ApiPatternsPatternIdFileRoute: ApiPatternsPatternIdFileRoute,
  ApiPatternsPatternIdUploadRoute: ApiPatternsPatternIdUploadRoute,
  ApiAdminUsersUserIdRoleRoute: ApiAdminUsersUserIdRoleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
